# Generated by Django 5.0.2 on 2024-04-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compliance_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxi_driver_pers_id', models.IntegerField()),
                ('orderer_pers_id', models.IntegerField()),
                ('distance', models.IntegerField(null=True)),
                ('distance2', models.IntegerField(null=True)),
                ('distance_time', models.IntegerField(null=True)),
                ('distance_time2', models.IntegerField(null=True)),
                ('amount', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Current_Orderers_Table',
            fields=[
                ('orderer_pers_id', models.IntegerField(primary_key=True, serialize=False)),
                ('service_type', models.CharField(max_length=100)),
                ('distance', models.IntegerField(null=True)),
                ('amount', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Current_Taxi_Drivers_Table',
            fields=[
                ('taxi_driver_pers_id', models.IntegerField(primary_key=True, serialize=False)),
                ('service_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Orderer',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('personal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('phone_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Potential_Current_Orderer',
            fields=[
                ('personal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('distance', models.IntegerField(null=True)),
                ('comfort', models.IntegerField(null=True)),
                ('economy', models.IntegerField(null=True)),
                ('business', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Received_Call_Table',
            fields=[
                ('taxi_driver_pers_id', models.IntegerField()),
                ('orderer_pers_id', models.IntegerField(primary_key=True, serialize=False)),
                ('distance', models.IntegerField(null=True)),
                ('distance2', models.IntegerField(null=True)),
                ('distance_time', models.IntegerField(null=True)),
                ('distance_time2', models.IntegerField(null=True)),
                ('amount', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Show_Data_Table',
            fields=[
                ('orderer_pers_id', models.IntegerField(primary_key=True, serialize=False)),
                ('show', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Taxi_Driver',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('personal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('phone_num', models.IntegerField()),
                ('car_series', models.CharField(max_length=100)),
                ('car_num', models.CharField(max_length=100)),
                ('car_color', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('Economy', 'Economy'), ('Comfort', 'Comfort'), ('Business', 'Business')], max_length=10)),
                ('account_num', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users_Accounts',
            fields=[
                ('personal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=100)),
                ('amount', models.IntegerField(null=True)),
            ],
        ),
    ]
